genevaers/User-Documentation

README.md
=> RemoveReadme

docs/_config.yml
=> EM-Baseurl-doc

docs/index.md
=> EM-Better-Index

docs/index.md
=> EM-LinkC`1

docs/Folder-A.md, docs/Folder-A/Topic-A1.md, docs/Folder-A/Topic-A2.md, docs/Folder-C.md, docs/Folder-C/Topic-C1.md, docs/Topic-B.md, docs/index.md
=> EM-Folders-&-TOCs-working

docs/Folder-A/Topic-A1.md, docs/Folder-A/Topic-A2.md, docs/Folder-C/Topic-C1.md, docs/Topic-B.md, docs/_config.yml
=> EM-Fix-TOCs

docs/_config.yml
=> EM-Config-YML

docs/02 User guide - start here/First steps.md, docs/03 Install.md, docs/04 Courses in basic skills.md, docs/04 Courses in basic skills/A03 - Course Guide.md, docs/04 Courses in basic skills/A04 - Course A - START HERE.md, docs/04 Courses in basic skills/A05 - Views and phases.md, docs/04 Courses in basic skills/A15 - Course A lessons.md, docs/04 Courses in basic skills/B01 - Course B - START HERE.md, docs/04 Courses in basic skills/B02 - Lookup paths.md, docs/04 Courses in basic skills/B12 - Course B lessons.md, docs/04 Courses in basic skills/C01 - Course C - START HERE.md, docs/04 Courses in basic skills/C02 - Optimize lookup paths.md, docs/10 How to use this product.md, docs/10 How to use this product/Stage5 - Run solution.md, docs/11 Typical goals.md, docs/12 Basic solutions.md, docs/13 Feature introductions.md
=> EM-Changes-02

docs/12 Basic solutions.md, docs/13 Feature introductions.md, docs/_config.yml
=> EM-Changes-03

docs/04 Courses in basic skills.md, docs/10 How to use this product.md, docs/12 Basic solutions.md, docs/13 Feature introductions.md
=> EM-Changes-04

docs/13 Feature introductions.md
=> EM-Changes-05

docs/Basic solutions.md, docs/Feature introductions.md, docs/User guide - start here/First steps.md
=> EM-Improve-01

docs/How to use this product/Stage1 - Define goal.md, docs/User guide - start here/First steps.md
=> EM-Improve-02

docs/How to use this product.md, docs/Lessons in basic skills.md, docs/Lessons in basic skills/A01 - How to learn quickly.md, docs/Lessons in basic skills/A02 - Introduction.md, docs/Lessons in basic skills/A03 - Course Guide.md, docs/index.md
=> EM-Fix-Lessons

docs/Lessons in basic skills.md, docs/Lessons in basic skills/Lesson A - Simple report/A01 - Lesson A - START HERE.md
=> EM-Various-fixes

docs/Sub-Programs.md, docs/User-Exits.md
=> EM-Fix-Links-02

docs/Feature introductions/Introduction F01 - Views.md
=> EM-Fix-Links-05

docs/Feature introductions/Introduction F01 - Views.md
=> EM-Fix-Links-06

docs/_config.yml
=> EM-GGD-Rename-stuff

docs/Gemfile.lock, docs/index.md
=> EM-Update-Home

AA Topics Markdown/Workbench Admin Guide/Dummy.md, AA Topics Markdown/Workbench Logic Text Intro/Dummy.md, AA Topics Markdown/Workbench Logic Text Summary Diagrams/Dummy.md, AA Topics Markdown/Workbench Logic Text Syntax/Dummy.md, AA Topics Markdown/Workbench Logic Text Types/Dummy.md, docs/Workbench Admin Guide/Dummy.md, docs/Workbench Logic Text Intro/Dummy.md, docs/Workbench Logic Text Summary Diagrams/Dummy.md
=> EM-04-Update-Dummy

AA Topics Markdown/Workbench Logic Text Syntax/Function ALL.md, docs/Workbench Logic Text Syntax/Function ALL.md
=> EM-One-Topic-Change

AC Common Markdown/Logic Text/Example Function ALL ECA.md, AS-Software/Prepare-Website-Params-Example.txt
=> EM-Fix-Params

.gitignore, AC Common Markdown/Logic Text/Introduction Function ALL.md, AD Expanded Common/Logic Text/Introduction Function ALL.md, AE Expanded Topics/Workbench Logic Text Syntax/Function ALL.md, AI Info/ERRORS Prepare-Website.txt, AI Info/REPORT Prepare-Website.txt, AI Info/TRACE Prepare-Website.txt, docs/Workbench Logic Text Syntax/Function ALL.md
=> EM-Examples-FIx

.gitignore, AA Topics Markdown/Workbench Logic Text Syntax/Function BATCHDATE.md, AC Common Markdown/Logic Text/Example Function BATCHDATE ECA.md, AC Common Markdown/Logic Text/Example Function BATCHDATE ERF.md, AC Common Markdown/Logic Text/Introduction Function ALL.md, AC Common Markdown/Logic Text/Introduction Function Batchdate.md, AC Common Markdown/Logic Text/Syntax Function BATCHDATE.md, docs/Workbench Logic Text Syntax/Function ALL.md, docs/Workbench Logic Text Syntax/Function BATCHDATE.md
=> EM-Function-BATCHDATE

docs/_config.yml
=> EM-LT-02-ConfigYML

docs/_config.yml
=> EM-LT-03-ConfigYML

AC Common Markdown/Logic Text/Rules for all Logic Text Common.md
=> EM-Fix-Rules-LT

AE-Expanded-Topics/Workbench Logic Text Syntax/Rules for all Logic Text.md, AI-Info/ERRORS Prepare-Website.txt, AI-Info/REPORT Prepare-Website.txt, AI-Info/TRACE Prepare-Website.txt, docs/Workbench Logic Text Syntax/Rules for all Logic Text.md
=> EM-Fix-Rules-02

docs/index.md
=> EM-Rename-02

All Markdown Topics/index.md
=> EM-More-Changes-01

Software/Prepare-Website-Params.txt
=> EM-New-Script-22

docs/Gemfile, docs/Gemfile.lock
=> Try-CommonMarker-01

Software/Prepare-Website-Params.txt, Software/Prepare-Website.ps1
=> EM-New-Script-30

All Markdown Topics/Errors in PE Programs/index.md
=> EM-New-Script-50

All Markdown Topics/Frequently Asked Questions (FAQ)/index.md, All Markdown Topics/REA Accounting Guide/index.md, All Markdown Topics/README.md, All Markdown Topics/Workbench Overviews/index.md
=> EM-New-Script-65

.gitignore
=> EM-GitIgnore-01

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function CURRENT.md, All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function PRIOR.md, Common Modules/Logic Text/Example Function PRIOR ECA.md, Common Modules/Logic Text/Example Function PRIOR ERF.md, Common Modules/Logic Text/Introduction Function FISCALDAY Level 3.md, Common Modules/Logic Text/Introduction Function PRIOR Level 3.md, Common Modules/Logic Text/Syntax Function PRIOR Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function CURRENT.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALDAY.md
=> EM-CURRENT-PRIOR

.gitignore
=> EM-gitignore-30

Common Modules/Logic Text/Example Function ALL ECA.md, Common Modules/Logic Text/Example Function ALL ERF.md, Common Modules/Logic Text/Example Function BATCHDATE ECA.md, Common Modules/Logic Text/Example Function DATE ECA.md, Common Modules/Logic Text/Example Function DATE ERF.md, Common Modules/Logic Text/Example Function DAYSBETWEEN ECA.md, Common Modules/Logic Text/Example Function DAYSBETWEEN ERF.md, Common Modules/Logic Text/Example Function FISCALDAY ECA.md, Common Modules/Logic Text/Example Function FISCALDAY ERF.md, Common Modules/Logic Text/Example Function PRIOR ECA.md, Common Modules/Logic Text/Example Function PRIOR ERF.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ALL.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function BATCHDATE.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function DATE.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function DAYSBETWEEN.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALDAY.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function PRIOR.md
=> EM-Better-LT

Common Modules/Test/Eugene.md, docs/About this website.md
=> EM-Changes-221031

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALMONTH.md, Common Modules/Logic Text/Example Function FISCALMONTH ECA.md, Common Modules/Logic Text/Example Function FISCALMONTH ERF.md, Common Modules/Logic Text/Introduction Function FISCALMONTH Level 3.md, Common Modules/Logic Text/Syntax Function FISCALMONTH Level 3.md
=> EM-FISCALMONTH

All Markdown Topics/How this website works.md, Common Modules/Logic Text/Rules for all Logic Text Common.md, docs/How this website works.md, docs/Workbench Logic Text Syntax/Rules for all Logic Text.md
=> EM-Rules-LT-01

All Markdown Topics/About this website.md, Common Modules/Test/Eugene.md, docs/About this website.md
=> EM-Cosmetic-01

Common Modules/Test/Gillian.md, docs/About this website.md
Signed-off-by: gillianh <gillianh@au1.ibm.com>
=> GH-Testing-01

All Markdown Topics/About this website.md, Common Modules/Test/Randall.md, docs/About this website.md
=> RN-Test-Include

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALQUARTER.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALQUARTER Level 3.md, Common Modules/Logic Text/Descriptions/Description Function FISCALQUARTER.md, Common Modules/Logic Text/Examples/Example Function FISCALQUARTER ECA.md, Common Modules/Logic Text/Examples/Example Function FISCALQUARTER ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function FISCALQUARTER Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALQUARTER.md
=> EM-LT-FQTR

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALYEAR.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALYEAR Level 3.md, Common Modules/Logic Text/Descriptions/Description Function FISCALQUARTER.md, Common Modules/Logic Text/Descriptions/Description Function FISCALYEAR.md, Common Modules/Logic Text/Examples/Example Function FISCALYEAR ECA.md, Common Modules/Logic Text/Examples/Example Function FISCALYEAR ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function FISCALYEAR Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALQUARTER.md
=> EM-FISCALYEAR

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function CURRENT.md, All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISFOUND.md, Common Modules/Logic Text/Consolidations/Consolidation Function ALL Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function BATCHDATE Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function DATE Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function DAYSBETWEEN Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALDAY Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALMONTH Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALQUARTER Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function FISCALYEAR Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISFOUND Level 3.md, Common Modules/Logic Text/Consolidations/Consolidation Function PRIOR Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISFOUND.md, Common Modules/Logic Text/Examples and Clipboard.md, Common Modules/Logic Text/Examples/Example Function ISFOUND ECA.md, Common Modules/Logic Text/Examples/Example Function ISFOUND ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISFOUND Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ALL.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function BATCHDATE.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function CURRENT.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function DATE.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function DAYSBETWEEN.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALDAY.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALMONTH.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALQUARTER.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALYEAR.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISFOUND.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function PRIOR.md
=> EM-Clipboard

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTFOUND.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISNOTFOUND Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISNOTFOUND.md, Common Modules/Logic Text/Examples/Example Function ISNOTFOUND ECA.md, Common Modules/Logic Text/Examples/Example Function ISNOTFOUND ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNOTFOUND Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTFOUND.md
=> EM-ISNOTFOUND

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTNULL.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISNOTNULL Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISNOTNULL.md, Common Modules/Logic Text/Examples/Example Function ISNOTNULL ECA.md, Common Modules/Logic Text/Examples/Example Function ISNOTNULL ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNOTNULL Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTNULL.md
=> EM-ISNOTNULL

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTNUMERIC.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISNOTNUMERIC Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISNOTNUMERIC.md, Common Modules/Logic Text/Examples/Example Function ISNOTNUMERIC ECA.md, Common Modules/Logic Text/Examples/Example Function ISNOTNUMERIC ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNOTNULL Level 3.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNOTNUMERIC Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTNULL.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTNUMERIC.md
=> EM-ISNOTNUMERIC

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTSPACES.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISNOTSPACES Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISNOTSPACES.md, Common Modules/Logic Text/Examples/Example Function ISNOTSPACES ECA.md, Common Modules/Logic Text/Examples/Example Function ISNOTSPACES ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNOTSPACES Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNOTSPACES.md
=> EM-ISNOTSPACES

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNUMERIC.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISNUMERIC Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISNUMERIC.md, Common Modules/Logic Text/Examples/Example Function ISNUMERIC ECA.md, Common Modules/Logic Text/Examples/Example Function ISNUMERIC ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISNUMERIC Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISNUMERIC.md
=> EM-ISNUMERIC

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISSPACES.md, Common Modules/Logic Text/Consolidations/Consolidation Function ISSPACES Level 3.md, Common Modules/Logic Text/Descriptions/Description Function ISSPACES.md, Common Modules/Logic Text/Examples/Example Function ISSPACES ECA.md, Common Modules/Logic Text/Examples/Example Function ISSPACES ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function ISSPACES Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function ISSPACES.md
=> EM-ISSPACES

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function MONTHSBETWEEN.md, Common Modules/Logic Text/Consolidations/Consolidation Function MONTHSBETWEEN Level 3.md, Common Modules/Logic Text/Descriptions/Description Function MONTHSBETWEEN.md, Common Modules/Logic Text/Examples/Example Function MONTHSBETWEEN ECA.md, Common Modules/Logic Text/Examples/Example Function MONTHSBETWEEN ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function MONTHSBETWEEN Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function MONTHSBETWEEN.md
=> EM-MONTHSBETWEEN

Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function MONTHSBETWEEN Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function MONTHSBETWEEN.md
=> EM-MONTHSBETWEEN-02

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNMONTH.md, Common Modules/Logic Text/Consolidations/Consolidation Function RUNMONTH Level 3.md, Common Modules/Logic Text/Descriptions/Description Function RUNMONTH.md, Common Modules/Logic Text/Examples/Example Function RUNMONTH ECA.md, Common Modules/Logic Text/Examples/Example Function RUNMONTH ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function RUNMONTH Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNMONTH.md
=> EM-RUNMONTH

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNDAY.md, All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNMONTH.md, All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNPERIOD.md, Common Modules/Logic Text/Consolidations/Consolidation Function RUNPERIOD Level 3.md, Common Modules/Logic Text/Descriptions/Description Function RUNPERIOD.md, Common Modules/Logic Text/Examples/Example Function RUNPERIOD ECA.md, Common Modules/Logic Text/Examples/Example Function RUNPERIOD ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function RUNPERIOD Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNDAY.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNMONTH.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNPERIOD.md
=> EM-RUNPERIOD

Common Modules/Logic Text/Descriptions/Description Function FISCALDAY.md, Common Modules/Logic Text/Descriptions/Description Function FISCALMONTH.md, Common Modules/Logic Text/Descriptions/Description Function FISCALQUARTER.md, Common Modules/Logic Text/Descriptions/Description Function FISCALYEAR.md, Common Modules/Logic Text/Descriptions/Description Function RUNDAY.md, Common Modules/Logic Text/Descriptions/Description Function RUNMONTH.md, Common Modules/Logic Text/Descriptions/Description Function RUNPERIOD.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALDAY.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALMONTH.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALQUARTER.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function FISCALYEAR.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNDAY.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNMONTH.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNPERIOD.md
=> EM-MR91-LINK

All Markdown Topics/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNQUARTER.md, Common Modules/Logic Text/Consolidations/Consolidation Function RUNQUARTER Level 3.md, Common Modules/Logic Text/Descriptions/Description Function RUNQUARTER.md, Common Modules/Logic Text/Examples/Example Function RUNQUARTER ECA.md, Common Modules/Logic Text/Examples/Example Function RUNQUARTER ERF.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag Function RUNQUARTER Level 3.md, docs/Workbench Logic Text Syntax/Syntax - functions/Syntax - function RUNQUARTER.md
=> EM-RUNQUARTER

All Markdown Topics/Workbench Logic Text Full Details/COLUMN & COL.nnn statements/COLUMN & COL.nnn statements (ECA).md, docs/Workbench Logic Text Full Details/COLUMN & COL.nnn statements/COLUMN & COL.nnn statements (ECA).md
=> EM-Full-Det-02

All Markdown Topics/Workbench Logic Text Full Details/COLUMN & COL.nnn statements/COLUMN & COL.nnn statements (FCC).md, Common Modules/Logic Text/Descriptions/Description COLUMN & COL.nnn FCC.md, Common Modules/Logic Text/Examples/Example COLUMN & COL.nnn FCC.md, Common Modules/Logic Text/Syntax diagrams/Syntax Diag COLUMN & COL.nnn FCC Level 3.md, docs/Workbench Logic Text Full Details/COLUMN & COL.nnn statements/COLUMN & COL.nnn statements (FCC).md
=> EM-Full-Det-03

All Markdown Topics/Workbench Logic Text Examples/Extract Column Assignment (ECA)/Examples - Functions (ECA).md, All Markdown Topics/Workbench Logic Text Examples/Extract Column Assignment (ECA)/Examples - Functions (ERF).md, Common Modules/Logic Text/Examples/CMExample ECA Functions A-L.md, Common Modules/Logic Text/Examples/CMExample ECA Functions M-Z.md, Common Modules/Logic Text/Examples/CMExample ERF Functions A-L.md, Common Modules/Logic Text/Examples/CMExample ERF Functions M-Z.md, docs/Workbench Logic Text Examples/Extract Column Assignment (ECA)/Examples - Functions (ECA).md, docs/Workbench Logic Text Examples/Extract Column Assignment (ECA)/Examples - Functions (ERF).md
=> EM-Ex-Funcs

Common Modules/Logic Text/Examples/CMExample COLUMN & COL.nnn FRF.md, docs/Workbench Logic Text Examples/Format Record Filter (FRF)/Examples - COLUMN & COL.nnn statements (FRF).md, docs/Workbench Logic Text Full Details/COLUMN & COL.nnn statements/COLUMN & COL.nnn statements (FRF).md
=> EM-Fix-Ex-02

YB Procedure for DITA raw MD/Readme Proc DITA.txt
=> EM-DITA-02

Common Modules/Logic Text/Syntax diagrams/CMSyntax Functions A-L Level 3.md, Common Modules/Logic Text/Syntax diagrams/CMSyntax Functions M-Z Level 3.md
Signed-off-by: rhness <rness001@gmail.com>
=> Change spelling of Functdion to Function

docs/Get Started/index.md, docs/Reference/Workbench/LogicText/Descriptions/Description-Comparison-BEGINS-WITH.md, docs/Reference/Workbench/LogicText/Descriptions/Description-Comparison-CONTAINS.md, docs/Reference/Workbench/LogicText/Descriptions/Description-Comparison-ENDS-WITH.md, docs/Reference/Workbench/LogicText/Descriptions/Description-IF-ERF.md, docs/Reference/Workbench/LogicText/Descriptions/Description-WRITE-ECL.md, docs/Reference/Workbench/LogicText/Descriptions/Description-WRITE-ERL.md, docs/Reference/Workbench/LogicText/Examples/CMExample-Comparison-BEGINS-WITH.md, docs/Reference/Workbench/LogicText/Examples/CMExample-Comparison-CONTAINS.md, docs/Reference/Workbench/LogicText/Examples/CMExample-Comparison-ENDS-WITH.md, docs/Reference/Workbench/LogicText/Examples/CMExample-WRITE-ECL.md, docs/Reference/Workbench/LogicText/Examples/CMExample-WRITE-ERL.md, docs/Reference/Workbench/LogicText/IFstatementsERF.md, docs/Reference/Workbench/LogicText/SELECTIFStatementERF.md, docs/Reference/Workbench/LogicText/SyntaxDiagrams/CMSyntax-Diag-IF-ERF-Level-3.md, docs/Reference/Workbench/LogicText/SyntaxDiagrams/CMSyntax-Diag-WRITE-ECL-Level-3.md, docs/Reference/Workbench/LogicText/WRITEstatementsECL.md, docs/Reference/Workbench/LogicText/WRITEstatementsERL.md, docs/Reference/Workbench/LogicTextECLStatements.md, docs/Reference/Workbench/LogicTextERFStatements.md, docs/Reference/Workbench/LogicTextERLStatements.md, docs/Setup and Use/index.md
WRITE statement reference has been added. The syntax diagrams need reviewing. Hopefully they are still valid.
=> New layout 

docs/Get Started/Concepts/Intro0_Introduction_to_Using_GenevaERS.md
Added small amount of simple material to introduction to WB, deleting duplicated material. Signed-off-by: Kip Twitchell <kip.twitchell@us.ibm.com>
=> Moved material from Workbench Docs

docs/Gemfile, docs/Gemfile.lock, docs/_config.yml
This reverts commit b0a9eaa660dfc987160bf425727a518843213584.
=> Revert "config and gemfile changes"

docs/AdvancedFeatures/MetaData/CreateControlRecord.md, docs/AdvancedFeatures/MetaData/CreateCopyView.md, docs/AdvancedFeatures/MetaData/CreateExtractView.md, docs/AdvancedFeatures/MetaData/CreateSummaryViewAggr.md, docs/AdvancedFeatures/MetaData/CreateSummaryViewDelimited.md, docs/AdvancedFeatures/MetaData/CreateSummaryViewNoAggr.md, docs/AdvancedFeatures/MetaData/CreateSummaryViewReportAggr.md, docs/AdvancedFeatures/MetaData/CreateSummaryViewReportDet.md, docs/AdvancedFeatures/OverviewDateFunctions.md, docs/AdvancedFeatures/index.md
I've added some info in the Advanced Features section about Date Processing, and Creating Control Records.
=> Date processing

docs/AdvancedFeatures/MetaData/CreateCopyView.md, docs/AdvancedFeatures/MetaData/CreateExtractView.md, docs/AdvancedFeatures/MetaData/CreateView.md
Look at 'Advanced Features' > 'Create views' for updated headings
=> Update Create View Headings

docs/Reference/GVBMR88_DD_Statements.md, docs/Reference/GVBMR88_Parameter_File_Syntax.md
GVBMR88 parameter descriptions
=> Parm descriptions
